--============TASK 4=========================================================================

--1--
select c.CustomerId,CONCAT(FirstName,' ',LastName) Name from
Customers c 
where c.CustomerId NOT IN (
select CustomerId from Orders
);
---------------------------------------------------------------------

--2--
select p.ProductId,p.ProductName from 
Products p
where p.ProductId In (
select ProductId from Inventory
where QuantityInStock>0
);
-----------------------------------------------------------------------

--3--
select sum(TotalAmount) TotalRevenueGenerated from Orders;
------------------------------------------------------------------------

--4--
--Sorry but there is no category mentioned in schema 

--5--
DECLARE @CustId int;
SET @CustId = 9;

select CustomerId , sum(TotalAmount) [Total Revenue Generated by a Customer] from Orders
where CustomerId= @CustId
Group by CustomerId;
-----------------------------------------------------------------------------------

--6--
select CONCAT(FirstName,' ',LastName) Names, TotalOrdersPlaced from 
Customers
where TotalOrdersPlaced=(
select max(totalOrdersPlaced) from Customers
)
order by CONCAT(FirstName,' ',LastName)
;
---------------------------------------------------------------------------------

--7--
SELECT TOP 1 
    p.ProductId,
    p.ProductName,
    SUM(od.Quantity) AS TotalQuantityOrdered
FROM Products p
JOIN OrderDetails od ON p.ProductId = od.ProductId
GROUP BY p.ProductId, p.ProductName
ORDER BY TotalQuantityOrdered DESC;

--8--
SELECT TOP 1 
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName, 
    SUM(od.Quantity * p.Price) AS TotalSpending
FROM Customers c
JOIN Orders o ON c.CustomerId = o.CustomerId
JOIN OrderDetails od ON o.OrderId = od.OrderId
JOIN Products p ON od.ProductId = p.ProductId
GROUP BY c.CustomerId, c.FirstName, c.LastName
ORDER BY TotalSpending DESC;

--9--
SELECT 
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    (
        SELECT AVG(TotalAmount)
        FROM Orders o
        WHERE o.CustomerId = c.CustomerId
    ) AS AverageOrderValue
FROM Customers c;
-------------------------------------------------------------------------

--10--
SELECT 
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    (
        SELECT COUNT(*)
        FROM Orders o
        WHERE o.CustomerId = c.CustomerId
    ) AS OrderCount
FROM Customers c;